# See Dependabot documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-github-actions:
        patterns: [ "*" ]
    reviewers:
      - "stuartmorgan"
    labels:
      - "team"
      - "team: infra"
      - "autosubmit"

  # Android example apps.
  - package-ecosystem: "gradle"
    directories:
      - /packages/path_provider/path_provider/example/android/app
      - /packages/path_provider/path_provider_android/example/android/app
    commit-message:
      prefix: "[dependabot]"
    schedule:
      interval: "weekly"
    labels:
      - "autosubmit"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  # Android packages (excluding example apps).
  - package-ecosystem: "gradle"
    directories:
      - /packages/path_provider/path_provider_android/android
    commit-message:
      prefix: "[dependabot]"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "autosubmit"
    groups:
      test-dependencies:
        patterns:
          - "androidx.test:*"
          - "io.mockk:*"
          - "junit:junit"
          - "org.mockito:*"
          - "org.robolectric:*"
      gradle-plugin:
        patterns:
          - "org.jetbrains.kotlin:kotlin-gradle-plugin"
      androidx:
        patterns:
          - "androidx.annotation:annotation"
    ignore:
      - dependency-name: "com.android.tools.build:gradle"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "junit:junit"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "org.mockito:*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "androidx.test:*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "org.robolectric:*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "io.mockk:mockk:*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
