# Build Device Info Plus Example
name: path_provider

concurrency:
  group: path_provider_${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

on:
  push:
    paths:
      - "path_provider/**"
      - "path_provider_android/**"
      - "path_provider_foundation/**"
      - "path_provider_linux/**"
      - "path_provider_ohos/**"
      - "path_provider_platform_interface/**"
      - "path_provider_windows/**"
      - ".github/workflows/path_provider.yaml"
      - "!**.md"
      - "!**.gitignore"
      - "*.yaml"

env:
  PLUGIN_SCOPE: "*path_provider*"
  PLUGIN_EXAMPLE_SCOPE: "*path_provider_example*"
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  android_example_build:
    runs-on: macos-13
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Make sh executable"
        run: chmod +x .github/workflows/scripts/*.sh
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh oh-3.22.0
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh android ./lib/main.dart

  android_integration_test:
    runs-on: macos-13
    timeout-minutes: 30
    strategy:
      matrix:
        android-api-level: [ 22, 26, 31 ]

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Make sh executable"
        run: chmod +x .github/workflows/scripts/*.sh
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh oh-3.22.0
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Bootstrap Workspace"
        run: melos bootstrap --scope="$PLUGIN_SCOPE"
      - name: "Android Integration Test"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.android-api-level }}
          cores: 3
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          profile: Nexus 5X
          script: ./.github/workflows/scripts/integration-test.sh android path_provider_example

  ios_example_build:
    runs-on: macos-13
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Make sh executable"
        run: chmod +x .github/workflows/scripts/*.sh
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh oh-3.22.0
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh ios ./lib/main.dart

  ios_integration_test:
    runs-on: macos-13
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Make sh executable"
        run: chmod +x .github/workflows/scripts/*.sh
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh oh-3.22.0
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Bootstrap Workspace"
        run: melos bootstrap --scope="$PLUGIN_SCOPE"
      - name: "Start Simulator"
        uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 14'
      - name: "Run Integration Test"
        run: ./.github/workflows/scripts/integration-test.sh ios path_provider_example

  macos_example_build:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Make sh executable"
        run: chmod +x .github/workflows/scripts/*.sh
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh oh-3.22.0
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh macos ./lib/main.dart

  macos_integration_test:
    runs-on: macos-13
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Make sh executable"
        run: chmod +x .github/workflows/scripts/*.sh
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh oh-3.22.0
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Bootstrap Workspace"
        run: melos bootstrap --scope="$PLUGIN_SCOPE"
      - name: "Run Integration Test"
        run: ./.github/workflows/scripts/integration-test.sh macos path_provider_example

  linux_example_build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Make sh executable"
        run: chmod +x .github/workflows/scripts/*.sh
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh oh-3.22.0
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh linux ./lib/main.dart

  linux_integration_test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Make sh executable"
        run: chmod +x .github/workflows/scripts/*.sh
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh oh-3.22.0
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Bootstrap Workspace"
        run: melos bootstrap --scope="$PLUGIN_SCOPE"
      - name: "Run Integration Test"
        run: ./.github/workflows/scripts/integration-test.sh linux path_provider_example

  windows_example_build:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Make sh executable"
        run: chmod +x .github/workflows/scripts/*.sh
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh oh-3.22.0
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh windows ./lib/main.dart

  windows_integration_test:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Make sh executable"
        run: chmod +x .github/workflows/scripts/*.sh
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh oh-3.22.0
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Bootstrap Workspace"
        run: melos.bat bootstrap --scope="$PLUGIN_SCOPE"
      - name: "Run Integration Test"
        run: ./.github/workflows/scripts/integration-test.sh windows path_provider_example

  web_example_build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Make sh executable"
        run: chmod +x .github/workflows/scripts/*.sh
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh oh-3.22.0
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: ./.github/workflows/scripts/build-examples.sh web ./lib/main.dart
